/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formeTurnir;

import controller.ClientController;
import domain.Turnir;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modeli.TableModelTurniri;

/**
 *
 * @author stefan
 */
public class FormPretragaTurnira extends javax.swing.JDialog {

    Locale jezik;

    public FormPretragaTurnira(java.awt.Frame parent, boolean modal, Locale jezik) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.jezik = jezik;
        namestiJezik();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPretraga = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnPretraga = new javax.swing.JButton();
        pnlNeevidentirani = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNeevidentirani = new javax.swing.JTable();
        btnAzuriraj = new javax.swing.JButton();
        pnlEvidentirani = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvidentirani = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPretraga.setText("Pretraga (naziv turnira):");

        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        btnPretraga.setText("Pretrazi");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        pnlNeevidentirani.setBorder(javax.swing.BorderFactory.createTitledBorder("Border"));

        tblNeevidentirani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblNeevidentirani);

        btnAzuriraj.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAzuriraj.setText("Azuriraj turnir");
        btnAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNeevidentiraniLayout = new javax.swing.GroupLayout(pnlNeevidentirani);
        pnlNeevidentirani.setLayout(pnlNeevidentiraniLayout);
        pnlNeevidentiraniLayout.setHorizontalGroup(
            pnlNeevidentiraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNeevidentiraniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNeevidentiraniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAzuriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        pnlNeevidentiraniLayout.setVerticalGroup(
            pnlNeevidentiraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNeevidentiraniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAzuriraj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEvidentirani.setBorder(javax.swing.BorderFactory.createTitledBorder("Border"));

        tblEvidentirani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEvidentirani);

        btnDetalji.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDetalji.setText("Detalji turnira");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEvidentiraniLayout = new javax.swing.GroupLayout(pnlEvidentirani);
        pnlEvidentirani.setLayout(pnlEvidentiraniLayout);
        pnlEvidentiraniLayout.setHorizontalGroup(
            pnlEvidentiraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvidentiraniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEvidentiraniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
        );
        pnlEvidentiraniLayout.setVerticalGroup(
            pnlEvidentiraniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEvidentiraniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetalji)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblPretraga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlNeevidentirani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlEvidentirani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPretraga)
                    .addComponent(btnPretraga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlEvidentirani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlNeevidentirani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
        String param = txtPretraga.getText();
        //((TableModelTurniri) tblEvidentirani.getModel()).setParametar(param);
    }//GEN-LAST:event_txtPretragaKeyReleased

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed

        int row = tblEvidentirani.getSelectedRow();

        if (row >= 0) {
            try {
                Turnir t = ((TableModelTurniri) tblEvidentirani.getModel()).getSelectedTurnir(row);

                String tip = t.getTip();
                switch (tip) {
                    case "Kup":
                        new FormDetaljiTurnira(this, rootPaneCheckingEnabled, t, jezik).setVisible(true);
                        break;
                    case "Liga":
                        new FormDetaljiLige(this, rootPaneCheckingEnabled, t, jezik).setVisible(true);
                        break;
                    default:
                        throw new AssertionError();
                }
                
                
            } catch (Exception ex) {
                Logger.getLogger(FormPretragaTurnira.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajActionPerformed

        int row = tblNeevidentirani.getSelectedRow();

        if (row >= 0) {
            Turnir t = ((TableModelTurniri) tblNeevidentirani.getModel()).getSelectedTurnir(row);
            try {
                switch (t.getTip()) {
                    case "Kup":
                        new FormAzuriranjeTurnira(this, true, t, jezik).setVisible(true);
                        break;
                    case "Liga":
                        new FormAzuriranjeLige(this, true, t, jezik).setVisible(true);
                        break;
                    default:
                        throw new AssertionError();
                }
            } catch (Exception ex) {
                Logger.getLogger(FormPretragaTurnira.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnAzurirajActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        try {
            String parametar = txtPretraga.getText();
            ArrayList<Turnir> turniri = ClientController.getInstance().getAllTurnir(parametar);

            if (!turniri.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        ResourceBundle.getBundle("resource/messages").getString("nasao"));
            } else {
                JOptionPane.showMessageDialog(this,
                        ResourceBundle.getBundle("resource/messages").getString("nije_nasao"));
            }

            TableModelTurniri tm1 = (TableModelTurniri) tblEvidentirani.getModel();
            tm1.clear();
            TableModelTurniri tm2 = (TableModelTurniri) tblNeevidentirani.getModel();
            tm2.clear();

            for (Turnir t : turniri) {
                if (t.getPobednik().equals("")) {
                    tm2.dodaj(t);
                } else {
                    tm1.dodaj(t);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(FormPretragaTurnira.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzuriraj;
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPretraga;
    private javax.swing.JPanel pnlEvidentirani;
    private javax.swing.JPanel pnlNeevidentirani;
    private javax.swing.JTable tblEvidentirani;
    private javax.swing.JTable tblNeevidentirani;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    final void popuniTabele() {
        try {
            ArrayList<Turnir> turniri = ClientController.getInstance().getAllTurnir();
            TableModelTurniri tm1 = (TableModelTurniri) tblEvidentirani.getModel();
            tm1.clear();
            TableModelTurniri tm2 = (TableModelTurniri) tblNeevidentirani.getModel();
            tm2.clear();

            for (Turnir t : turniri) {
                if (t.getPobednik().equals("")) {
                    tm2.dodaj(t);
                } else {
                    tm1.dodaj(t);
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(FormPretragaTurnira.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void namestiJezik() {
        ResourceBundle bundle = ResourceBundle.getBundle("resource/messages");

        setTitle(bundle.getString("pretraga_turnir"));

        lblPretraga.setText(bundle.getString("search_turnir"));

        pnlEvidentirani.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("gotovi")));
        pnlNeevidentirani.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("u_toku")));

        btnAzuriraj.setText(bundle.getString("azuriraj_turnir"));
        btnDetalji.setText(bundle.getString("detalji_turnir"));
        btnPretraga.setText(bundle.getString("pretrazi"));

        String[] kolone = {"ID:", bundle.getString("naziv"), bundle.getString("tip_turnira"),
            bundle.getString("datum_pocetka"), bundle.getString("datum_kraja"), bundle.getString("pobednik_turnir")};

        try {
            ArrayList<Turnir> turniri = ClientController.getInstance().getAllTurnir();
            TableModelTurniri tm1 = new TableModelTurniri();
            tm1.setKolone(kolone);
            tblEvidentirani.setModel(tm1);

            TableModelTurniri tm2 = new TableModelTurniri();
            tm2.setKolone(kolone);
            tblNeevidentirani.setModel(tm2);

            for (Turnir t : turniri) {
                if (t.getPobednik().equals("")) {
                    tm2.dodaj(t);
                } else {
                    tm1.dodaj(t);
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(FormPretragaTurnira.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
