/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formeTurnir;

import domain.Turnir;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JDialog;
import modeli.TableModelStandings;

/**
 *
 * @author stefan
 */
public class FormStandings extends javax.swing.JDialog {

    Turnir t;
    TableModelStandings tm;
    Locale jezik;
    /**
     * Creates new form FormStandings
     */
    public FormStandings(JDialog parent, boolean modal, Turnir t, Locale jezik) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.t = t;
        lblNazivTurnira.setText(this.t.getNazivTurnira());
        rbTotal.setSelected(true);
        this.jezik=jezik;
        namestiJezik();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNazivTurnira = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStandings = new javax.swing.JTable();
        rbTotal = new javax.swing.JRadioButton();
        rbHome = new javax.swing.JRadioButton();
        rbAway = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNazivTurnira.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNazivTurnira.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNazivTurnira.setText("jLabel1");

        tblStandings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStandings);

        rbTotal.setText("Total");
        rbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTotalActionPerformed(evt);
            }
        });

        rbHome.setText("Home");
        rbHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHomeActionPerformed(evt);
            }
        });

        rbAway.setText("Away");
        rbAway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAwayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNazivTurnira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rbTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbHome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbAway)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNazivTurnira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTotal)
                    .addComponent(rbHome)
                    .addComponent(rbAway))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTotalActionPerformed
        rbTotal.setSelected(true);
        rbHome.setSelected(false);
        rbAway.setSelected(false);
        
        tm.setTotalHomeAway(0);
    }//GEN-LAST:event_rbTotalActionPerformed

    private void rbHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHomeActionPerformed
        rbTotal.setSelected(false);
        rbHome.setSelected(true);
        rbAway.setSelected(false);
        
        tm.setTotalHomeAway(1);
    }//GEN-LAST:event_rbHomeActionPerformed

    private void rbAwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAwayActionPerformed
        rbTotal.setSelected(false);
        rbHome.setSelected(false);
        rbAway.setSelected(true);
        
        tm.setTotalHomeAway(2);
    }//GEN-LAST:event_rbAwayActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNazivTurnira;
    private javax.swing.JRadioButton rbAway;
    private javax.swing.JRadioButton rbHome;
    private javax.swing.JRadioButton rbTotal;
    private javax.swing.JTable tblStandings;
    // End of variables declaration//GEN-END:variables
    
    private void namestiJezik() {
        ResourceBundle bundle = ResourceBundle.getBundle("resource/messages");
        
        setTitle(bundle.getString("tabela"));
        
        rbTotal.setText(bundle.getString("rb_total"));
        rbHome.setText(bundle.getString("rb_home"));
        rbAway.setText(bundle.getString("rb_away"));
        
        String[] kolone = {bundle.getString("tim"), bundle.getString("pobede"), bundle.getString("pobede_p"),
            bundle.getString("porazi_p"), bundle.getString("porazi"), bundle.getString("gol_razlika"), bundle.getString("poeni")};
        tm = new TableModelStandings(t);
        tm.setKolone(kolone);
        tblStandings.setModel(tm);
        
    }
}
