/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formeTurnir;

import domain.Utakmica;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author stefan
 */
public class FormPenali extends javax.swing.JDialog {

    Utakmica u;
    Locale jezik;
    /**
     * Creates new form FormPenali
     */
    public FormPenali(JDialog parent, boolean modal, Utakmica u, Locale jezik) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Penali");
        this.u=u;
        //this.row = row;
        lblPrviTim.setText(u.getPrviTim().getNazivTima());
        lblDrugiTim.setText(u.getDrugiTim().getNazivTima());
        this.jezik = jezik;
        namestiJezik();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrviTim = new javax.swing.JLabel();
        lblDrugiTim = new javax.swing.JLabel();
        txtGoloviPrvi = new javax.swing.JFormattedTextField();
        txtGoloviDrugi = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPrviTim.setText("jLabel1");

        lblDrugiTim.setText("jLabel2");

        txtGoloviPrvi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtGoloviDrugi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel1.setText(":");

        btnIzmeni.setText("Potvrdi");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrviTim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGoloviPrvi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGoloviDrugi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDrugiTim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrviTim)
                    .addComponent(lblDrugiTim)
                    .addComponent(txtGoloviPrvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGoloviDrugi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if (txtGoloviPrvi.getText().isEmpty() || txtGoloviDrugi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    ResourceBundle.getBundle("resource/messages").getString("polja_msg"));
            return;
        }
        
        int penaliPrvi = Integer.parseInt(txtGoloviPrvi.getText());
        int penaliDrugi = Integer.parseInt(txtGoloviDrugi.getText());

        if (penaliPrvi==penaliDrugi) {

            JOptionPane.showMessageDialog(this, 
                    ResourceBundle.getBundle("resource/messages").getString("penali_nereseno"));
            return;
        }

        u.setPenaliPrvi(penaliPrvi);
        u.setPenaliDrugi(penaliDrugi);
        u.setPobednik(penaliPrvi > penaliDrugi ? u.getPrviTim() : u.getDrugiTim());

        this.dispose();
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDrugiTim;
    private javax.swing.JLabel lblPrviTim;
    private javax.swing.JFormattedTextField txtGoloviDrugi;
    private javax.swing.JFormattedTextField txtGoloviPrvi;
    // End of variables declaration//GEN-END:variables

    private void namestiJezik() {
        ResourceBundle bundle = ResourceBundle.getBundle("resource/messages");
        
        setTitle(bundle.getString("penali"));
        
        btnIzmeni.setText(bundle.getString("confirm"));
    }
}
