/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formeTim;

import controller.ClientController;
import domain.Grad;
import domain.Igrac;
import domain.Tim;
import domain.Vaterpolista;
import forme.MainForm;
import java.util.ArrayList;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modeli.TableModelIgraci;

/**
 *
 * @author stefan
 */
public class FormNoviTim extends javax.swing.JDialog {

    Locale jezik;
    /**
     * Creates new form FormNoviTim
     */
    public FormNoviTim(java.awt.Frame parent, boolean modal, Locale jezik) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        popuniGradove();
        popuniIgrace();
        this.jezik = jezik;
        namestiJezik();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTim = new javax.swing.JPanel();
        lblGrad = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        cmbGrad = new javax.swing.JComboBox();
        pnlIgraci = new javax.swing.JPanel();
        lblIgrac = new javax.swing.JLabel();
        lblPozicija = new javax.swing.JLabel();
        lblBrojKapice = new javax.swing.JLabel();
        cmbIgraci = new javax.swing.JComboBox();
        cmbPozicija = new javax.swing.JComboBox<>();
        txtBrojKapice = new javax.swing.JFormattedTextField();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIgraci = new javax.swing.JTable();
        btnDodajTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlTim.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos tima"));

        lblGrad.setText("Grad:");

        lblNaziv.setText("Naziv:");

        cmbGrad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        pnlIgraci.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos igraca"));

        lblIgrac.setText("Igrac");

        lblPozicija.setText("Pozicija");

        lblBrojKapice.setText("Broj kapice");

        cmbIgraci.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPozicija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Golman", "Bek", "Sidro", "Krilo" }));

        txtBrojKapice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtBrojKapice.setText("1");
        txtBrojKapice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojKapiceActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj igraca");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi igraca");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        tblIgraci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblIgraci);

        javax.swing.GroupLayout pnlIgraciLayout = new javax.swing.GroupLayout(pnlIgraci);
        pnlIgraci.setLayout(pnlIgraciLayout);
        pnlIgraciLayout.setHorizontalGroup(
            pnlIgraciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIgraciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIgraciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlIgraciLayout.createSequentialGroup()
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlIgraciLayout.createSequentialGroup()
                        .addGroup(pnlIgraciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPozicija)
                            .addComponent(lblBrojKapice)
                            .addComponent(lblIgrac))
                        .addGap(71, 71, 71)
                        .addGroup(pnlIgraciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbIgraci, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPozicija, 0, 635, Short.MAX_VALUE)
                            .addComponent(txtBrojKapice))))
                .addContainerGap())
        );
        pnlIgraciLayout.setVerticalGroup(
            pnlIgraciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIgraciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIgraciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIgrac)
                    .addComponent(cmbIgraci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIgraciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPozicija))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIgraciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojKapice)
                    .addComponent(txtBrojKapice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIgraciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDodajTim.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnDodajTim.setText("Dodaj tim");
        btnDodajTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTimLayout = new javax.swing.GroupLayout(pnlTim);
        pnlTim.setLayout(pnlTimLayout);
        pnlTimLayout.setHorizontalGroup(
            pnlTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTimLayout.createSequentialGroup()
                        .addComponent(pnlIgraci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlTimLayout.createSequentialGroup()
                        .addGroup(pnlTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNaziv)
                            .addComponent(lblGrad))
                        .addGap(79, 79, 79)
                        .addGroup(pnlTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv)
                            .addComponent(cmbGrad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(pnlTimLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btnDodajTim, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTimLayout.setVerticalGroup(
            pnlTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrad)
                    .addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlIgraci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDodajTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajTimActionPerformed

        try {
            
            if (txtNaziv.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                        ResourceBundle.getBundle("resource/messages").getString("polja_msg"));
                return;
            }

            String naziv = txtNaziv.getText();
            Grad grad = (Grad) cmbGrad.getSelectedItem();

            TableModelIgraci tm = (TableModelIgraci) tblIgraci.getModel();

            Tim tim = new Tim(null, naziv, grad, tm.getLista());

            ClientController.getInstance().addTim(tim);
            resetujFormu();
            JOptionPane.showMessageDialog(this, 
                    ResourceBundle.getBundle("resource/messages").getString("kreiran_tim_msg"));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("resource.messages").getString(ex.getMessage()));
            //Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDodajTimActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int row = tblIgraci.getSelectedRow();

        if (row >= 0) {
            TableModelIgraci tm = (TableModelIgraci) tblIgraci.getModel();
            cmbIgraci.addItem(tm.obrisiIgraca(row));
        }
        
        brojKapice();
        
        cmbIgraci.setEnabled(true);
        btnDodaj.setEnabled(true);
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        if (txtBrojKapice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    ResourceBundle.getBundle("resource/messages").getString("polja_msg"));
            return;
        }

        int brojKapice = Integer.parseInt(txtBrojKapice.getText());
        String pozicija = (String) cmbPozicija.getSelectedItem();
        Vaterpolista v = (Vaterpolista) cmbIgraci.getSelectedItem();               

        Igrac i = new Igrac(null, brojKapice, pozicija, v);

        if (brojKapice>99 || brojKapice<0) {
            JOptionPane.showMessageDialog(this, 
                    ResourceBundle.getBundle("resource/messages").getString("kapica099"));
            return;
        }
        
        TableModelIgraci tm = (TableModelIgraci) tblIgraci.getModel();
        
        if (tm.postojiBrojKapice(brojKapice)) {
            JOptionPane.showMessageDialog(this, 
                    ResourceBundle.getBundle("resource/messages").getString("kapica_zauzeta"));
            return;
        }

        tm.dodajIgraca(i);
        
        cmbIgraci.removeItem(cmbIgraci.getSelectedItem());
        if (cmbIgraci.getModel().getSize() == 0) { 
            cmbIgraci.setEnabled(false);
            btnDodaj.setEnabled(false);
        }
        txtBrojKapice.setText(Integer.toString(tm.getLista().size()+1));
    }//GEN-LAST:event_btnDodajActionPerformed

    private void txtBrojKapiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojKapiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojKapiceActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajTim;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JComboBox cmbGrad;
    private javax.swing.JComboBox cmbIgraci;
    private javax.swing.JComboBox<String> cmbPozicija;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrojKapice;
    private javax.swing.JLabel lblGrad;
    private javax.swing.JLabel lblIgrac;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblPozicija;
    private javax.swing.JPanel pnlIgraci;
    private javax.swing.JPanel pnlTim;
    private javax.swing.JTable tblIgraci;
    private javax.swing.JFormattedTextField txtBrojKapice;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

    private void popuniGradove() {
        try {
            ArrayList<Grad> gradovi = ClientController.getInstance().getAllGrad();

            cmbGrad.removeAllItems();

            for (Grad grad : gradovi) {
                cmbGrad.addItem(grad);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniIgrace() {
        try {
            ArrayList<Vaterpolista> vaterpolisti = ClientController.getInstance().getAllVaterpolista();
            
            
            ArrayList<Igrac> zauzetiIgraci = new ArrayList<>();
            
            for (Igrac igrac : ClientController.getInstance().getAllIgrac()) {
                zauzetiIgraci.add(igrac);
            }
                       
            
            cmbIgraci.removeAllItems();

            for (Vaterpolista vaterpolista : vaterpolisti) {
                boolean slobodan = true;
                for (Igrac igrac : zauzetiIgraci) {
                    if (vaterpolista.getVaterpolistaID().equals(igrac.getVaterpolista().getVaterpolistaID())) {
                        slobodan = false;
                        break;
                    }
                }
                if (slobodan) {
                    cmbIgraci.addItem(vaterpolista);
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void resetujFormu() {
        txtNaziv.setText("");
        txtBrojKapice.setText("1");
        popuniIgrace();
        TableModelIgraci tm = (TableModelIgraci) tblIgraci.getModel();
        tm.getLista().clear();
        tm.fireTableDataChanged();
    }
    
    private void brojKapice() {
        int bk = 1;
        for (Igrac igrac : ((TableModelIgraci) tblIgraci.getModel()).getLista()) {
            if (igrac.getBrojKapice()==bk) {
                bk++;
            } else break;
        }
        
        txtBrojKapice.setText(Integer.toString(bk));
    }
    
    private void namestiJezik() {
        ResourceBundle bundle = ResourceBundle.getBundle("resource/messages");
        
        setTitle(bundle.getString("novi_tim"));
        
        pnlTim.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("tim_unos")));
        pnlIgraci.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("igraci_unos")));
        
        lblBrojKapice.setText(bundle.getString("broj_kapice"));
        lblGrad.setText(bundle.getString("grad"));
        lblIgrac.setText(bundle.getString("igrac"));
        lblNaziv.setText(bundle.getString("naziv"));
        lblPozicija.setText(bundle.getString("pozicija"));
        
        btnDodaj.setText(bundle.getString("dodaj_igraca"));
        btnObrisi.setText(bundle.getString("ukloni_igraca"));
        btnDodajTim.setText(bundle.getString("dodaj_tim"));
        
        String[] kolone = {bundle.getString("broj_kapice"), bundle.getString("vaterpolista") + ":", bundle.getString("pozicija")};
        TableModelIgraci model = new TableModelIgraci();
        model.setKolone(kolone);
        tblIgraci.setModel(model);
        
    }
}
